import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Truck, Plus, PackageCheck } from "lucide-react";
import { toast } from "sonner";
import { MetricCard, ModuleHeader, PedidoSelect, dateBr, useConjuntos, usePedidos } from "@/components/operations";

export const Route = createFileRoute("/_authenticated/expedicao")({
  head: () => ({ meta: [{ title: "Expedição | Omega Service ERP" }, { name: "description", content: "Romaneios e expedições parciais de conjuntos liberados." }, { property: "og:title", content: "Expedição | Omega Service ERP" }, { property: "og:description", content: "Romaneios e expedições parciais de conjuntos liberados." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ExpedicaoPage,
});
type Romaneio = { id: string; numero: string; pedido_id: string; data_romaneio: string; destino: string | null; transporte: string | null; status: string; observacoes: string | null };
type Item = { id: string; romaneio_id: string; conjunto_id: string; quantidade: number; peso_kg: number | null };

function ExpedicaoPage() {
  const qc = useQueryClient(); const { data: pedidos = [] } = usePedidos(); const [pedidoId, setPedidoId] = useState(""); const [novo, setNovo] = useState(false); const [itemRomaneio, setItemRomaneio] = useState<Romaneio | null>(null);
  const [form, setForm] = useState({ numero: "", destino: "", transporte: "", observacoes: "" }); const [itemForm, setItemForm] = useState({ conjunto_id: "", quantidade: "1", peso_kg: "" });
  useEffect(() => { if (!pedidoId && pedidos[0]) setPedidoId(pedidos[0].id); }, [pedidoId, pedidos]); const { data: conjuntos = [] } = useConjuntos(pedidoId);
  const { data: romaneios = [] } = useQuery({ queryKey: ["romaneios", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("romaneios").select("*").eq("pedido_id", pedidoId).order("created_at", { ascending: false }); if (error) throw error; return data as Romaneio[]; } });
  const { data: itens = [] } = useQuery({ queryKey: ["romaneio-itens", pedidoId, romaneios.map((r) => r.id).join(",")], enabled: romaneios.length > 0, queryFn: async () => { const { data, error } = await supabase.from("romaneio_itens").select("*").in("romaneio_id", romaneios.map((r) => r.id)); if (error) throw error; return data as Item[]; } });
  const enviados = useMemo(() => itens.reduce<Record<string, number>>((a, i) => { const status = romaneios.find((r) => r.id === i.romaneio_id)?.status; if (status !== "cancelado") a[i.conjunto_id] = (a[i.conjunto_id] ?? 0) + Number(i.quantidade); return a; }, {}), [itens, romaneios]);
  const liberados = conjuntos.filter((c) => c.liberado_qualidade && (enviados[c.id] ?? 0) < Number(c.quantidade)); const entregue = romaneios.filter((r) => r.status === "entregue").length; const expedido = romaneios.filter((r) => r.status === "expedido").length;
  const criar = useMutation({ mutationFn: async () => { if (!pedidoId) return; const { error } = await supabase.from("romaneios").insert({ pedido_id: pedidoId, numero: form.numero || `ROM-${Date.now().toString().slice(-8)}`, destino: form.destino || null, transporte: form.transporte || null, observacoes: form.observacoes || null }); if (error) throw error; }, onSuccess: () => { toast.success("Romaneio criado"); setNovo(false); setForm({ numero: "", destino: "", transporte: "", observacoes: "" }); qc.invalidateQueries({ queryKey: ["romaneios", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  const addItem = useMutation({ mutationFn: async () => { if (!itemRomaneio || !itemForm.conjunto_id) return; const { error } = await supabase.from("romaneio_itens").insert({ romaneio_id: itemRomaneio.id, conjunto_id: itemForm.conjunto_id, quantidade: Number(itemForm.quantidade), peso_kg: itemForm.peso_kg ? Number(itemForm.peso_kg) : null }); if (error) throw error; }, onSuccess: () => { toast.success("Conjunto adicionado"); setItemRomaneio(null); setItemForm({ conjunto_id: "", quantidade: "1", peso_kg: "" }); qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  const statusMut = useMutation({ mutationFn: async ({ id, status }: { id: string; status: string }) => { const { error } = await supabase.from("romaneios").update({ status }).eq("id", id); if (error) throw error; }, onSuccess: () => { toast.success("Situação atualizada"); qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-6"><ModuleHeader title="Expedição" description="Romaneios parciais e controle do saldo liberado para entrega." icon={Truck} action={<Button onClick={() => setNovo(true)} disabled={!pedidoId}><Plus className="mr-2 h-4 w-4" />Novo romaneio</Button>} /><PedidoSelect pedidos={pedidos} value={pedidoId} onChange={setPedidoId} />
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><MetricCard label="Liberados com saldo" value={liberados.length} tone="success" /><MetricCard label="Em preparação" value={romaneios.filter((r) => r.status === "preparacao").length} /><MetricCard label="Em trânsito" value={expedido} tone="warning" /><MetricCard label="Entregues" value={entregue} tone="success" /></div>
  <Card><CardHeader><CardTitle className="text-base">Romaneios do pedido</CardTitle></CardHeader><CardContent className="space-y-3">{romaneios.length ? romaneios.map((r) => { const ris = itens.filter((i) => i.romaneio_id === r.id); return <div key={r.id} className="border-b pb-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="font-mono text-sm font-semibold">{r.numero}</div><div className="text-xs text-muted-foreground">{dateBr(r.data_romaneio)} · {r.destino || "Destino não informado"} · {ris.length} conjunto(s)</div></div><div className="flex items-center gap-2"><Badge variant={r.status === "cancelado" ? "destructive" : "outline"}>{r.status}</Badge>{r.status === "preparacao" && <><Button size="sm" variant="outline" onClick={() => setItemRomaneio(r)}><PackageCheck className="mr-2 h-4 w-4" />Adicionar</Button><Button size="sm" onClick={() => statusMut.mutate({ id: r.id, status: "expedido" })} disabled={!ris.length}>Expedir</Button></>}{r.status === "expedido" && <Button size="sm" onClick={() => statusMut.mutate({ id: r.id, status: "entregue" })}>Confirmar entrega</Button>}</div></div>{ris.length > 0 && <div className="mt-2 flex flex-wrap gap-2">{ris.map((i) => { const c = conjuntos.find((x) => x.id === i.conjunto_id); return <span key={i.id} className="rounded bg-muted px-2 py-1 text-xs">{c?.tag} · {i.quantidade} un.</span>; })}</div>}</div>; }) : <Empty text="Nenhum romaneio criado." />}</CardContent></Card>
  <Card><CardHeader><CardTitle className="text-base">Saldo liberado pela Qualidade</CardTitle></CardHeader><CardContent className="space-y-2">{conjuntos.filter((c) => c.liberado_qualidade).length ? conjuntos.filter((c) => c.liberado_qualidade).map((c) => <div key={c.id} className="flex justify-between border-b py-2 text-sm"><span><strong className="font-mono">{c.tag}</strong> · {c.descricao}</span><span>{Number(c.quantidade) - (enviados[c.id] ?? 0)} de {c.quantidade} disponíveis</span></div>) : <Empty text="Nenhum conjunto liberado para expedição." />}</CardContent></Card>
  <Dialog open={novo} onOpenChange={setNovo}><DialogContent><DialogHeader><DialogTitle>Novo romaneio</DialogTitle></DialogHeader><Field label="Número"><Input placeholder="Gerado automaticamente se vazio" value={form.numero} onChange={(e) => setForm({ ...form, numero: e.target.value })} /></Field><Field label="Destino"><Input value={form.destino} onChange={(e) => setForm({ ...form, destino: e.target.value })} /></Field><Field label="Transporte"><Input placeholder="Próprio, transportadora ou retirada" value={form.transporte} onChange={(e) => setForm({ ...form, transporte: e.target.value })} /></Field><Field label="Observações"><Textarea value={form.observacoes} onChange={(e) => setForm({ ...form, observacoes: e.target.value })} /></Field><DialogFooter><Button variant="outline" onClick={() => setNovo(false)}>Cancelar</Button><Button onClick={() => criar.mutate()}>Criar</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(itemRomaneio)} onOpenChange={(o) => !o && setItemRomaneio(null)}><DialogContent><DialogHeader><DialogTitle>Adicionar ao romaneio</DialogTitle></DialogHeader><Field label="Conjunto liberado"><Select value={itemForm.conjunto_id} onValueChange={(v) => setItemForm({ ...itemForm, conjunto_id: v })}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{liberados.map((c) => <SelectItem key={c.id} value={c.id}>{c.tag} · saldo {Number(c.quantidade) - (enviados[c.id] ?? 0)}</SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-3"><Field label="Quantidade"><Input type="number" min="0.001" step="0.001" value={itemForm.quantidade} onChange={(e) => setItemForm({ ...itemForm, quantidade: e.target.value })} /></Field><Field label="Peso (kg)"><Input type="number" value={itemForm.peso_kg} onChange={(e) => setItemForm({ ...itemForm, peso_kg: e.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setItemRomaneio(null)}>Cancelar</Button><Button onClick={() => addItem.mutate()} disabled={!itemForm.conjunto_id}>Adicionar</Button></DialogFooter></DialogContent></Dialog></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function Empty({ text }: { text: string }) { return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>; }