import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Receipt, Plus, Banknote } from "lucide-react";
import { toast } from "sonner";
import { MetricCard, ModuleHeader, PedidoSelect, dateBr, moneyBr, usePedidos } from "@/components/operations";

export const Route = createFileRoute("/_authenticated/medicao")({
  head: () => ({ meta: [{ title: "Medição | Omega Service ERP" }, { name: "description", content: "Medições, notas fiscais, vencimentos e pagamentos por pedido." }, { property: "og:title", content: "Medição | Omega Service ERP" }, { property: "og:description", content: "Medições, notas fiscais, vencimentos e pagamentos por pedido." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: MedicaoPage,
});
type Medicao = { id: string; numero: string; valor_medido: number; status: string; periodo_inicio: string | null; periodo_fim: string | null; observacoes: string | null };
type Nota = { id: string; medicao_id: string | null; numero: string; data_emissao: string; data_vencimento: string | null; valor: number; status: string; data_pagamento: string | null; valor_recebido: number };

function MedicaoPage() {
  const qc = useQueryClient(); const { data: pedidos = [] } = usePedidos(); const [pedidoId, setPedidoId] = useState(""); const [novaMedicao, setNovaMedicao] = useState(false); const [novaNota, setNovaNota] = useState(false);
  const [mf, setMf] = useState({ numero: "", inicio: "", fim: "", valor: "", observacoes: "" }); const [nf, setNf] = useState({ medicao_id: "", numero: "", emissao: new Date().toISOString().slice(0,10), vencimento: "", valor: "" });
  useEffect(() => { if (!pedidoId && pedidos[0]) setPedidoId(pedidos[0].id); }, [pedidoId, pedidos]); const pedido = pedidos.find((p) => p.id === pedidoId);
  const { data: medicoes = [] } = useQuery({ queryKey: ["medicoes", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("medicoes").select("*").eq("pedido_id", pedidoId).order("created_at", { ascending: false }); if (error) throw error; return data as Medicao[]; } });
  const { data: notas = [] } = useQuery({ queryKey: ["notas", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("notas_fiscais").select("*").eq("pedido_id", pedidoId).order("data_emissao", { ascending: false }); if (error) throw error; return data as Nota[]; } });
  const medido = medicoes.filter((m) => m.status === "aprovada").reduce((s, m) => s + Number(m.valor_medido), 0); const faturado = notas.filter((n) => n.status !== "cancelada").reduce((s, n) => s + Number(n.valor), 0); const recebido = notas.reduce((s, n) => s + Number(n.valor_recebido), 0); const vencido = notas.filter((n) => n.status !== "paga" && n.data_vencimento && new Date(n.data_vencimento) < new Date()).reduce((s, n) => s + Number(n.valor) - Number(n.valor_recebido), 0);
  const criarMedicao = useMutation({ mutationFn: async () => { if (!pedidoId) return; const { error } = await supabase.from("medicoes").insert({ pedido_id: pedidoId, numero: mf.numero || `MED-${Date.now().toString().slice(-8)}`, periodo_inicio: mf.inicio || null, periodo_fim: mf.fim || null, valor_medido: Number(mf.valor || 0), observacoes: mf.observacoes || null }); if (error) throw error; }, onSuccess: () => { toast.success("Medição criada"); setNovaMedicao(false); setMf({ numero: "", inicio: "", fim: "", valor: "", observacoes: "" }); qc.invalidateQueries({ queryKey: ["medicoes", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  const medicaoStatus = useMutation({ mutationFn: async ({ id, status }: { id: string; status: string }) => { const { error } = await supabase.from("medicoes").update({ status }).eq("id", id); if (error) throw error; }, onSuccess: () => qc.invalidateQueries({ queryKey: ["medicoes", pedidoId] }), onError: (e: Error) => toast.error(e.message) });
  const criarNota = useMutation({ mutationFn: async () => { if (!pedidoId) return; const { error } = await supabase.from("notas_fiscais").insert({ pedido_id: pedidoId, medicao_id: nf.medicao_id || null, numero: nf.numero, data_emissao: nf.emissao, data_vencimento: nf.vencimento || null, valor: Number(nf.valor || 0) }); if (error) throw error; }, onSuccess: () => { toast.success("Nota fiscal registrada"); setNovaNota(false); setNf({ medicao_id: "", numero: "", emissao: new Date().toISOString().slice(0,10), vencimento: "", valor: "" }); qc.invalidateQueries({ queryKey: ["notas", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  const pagar = useMutation({ mutationFn: async (n: Nota) => { const { error } = await supabase.from("notas_fiscais").update({ status: "paga", data_pagamento: new Date().toISOString().slice(0,10), valor_recebido: Number(n.valor) }).eq("id", n.id); if (error) throw error; }, onSuccess: () => { toast.success("Pagamento confirmado"); qc.invalidateQueries({ queryKey: ["notas", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  const encerrar = useMutation({ mutationFn: async () => { if (!pedidoId) return; const { data: conjuntos, error: ce } = await supabase.from("pedido_conjuntos").select("status").eq("pedido_id", pedidoId); if (ce) throw ce; if (!conjuntos?.length || conjuntos.some((c) => c.status !== "expedido" && c.status !== "concluido")) throw new Error("Todos os conjuntos precisam estar expedidos"); if (recebido < Number(pedido?.valor_total ?? 0)) throw new Error("O valor total do pedido ainda não foi recebido"); const { error } = await supabase.from("pedidos").update({ status: "concluido" }).eq("id", pedidoId); if (error) throw error; }, onSuccess: () => { toast.success("Pedido encerrado"); qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-6"><ModuleHeader title="Medição" description="Medições, faturamento, vencimentos, pagamentos e encerramento." icon={Receipt} action={<div className="flex gap-2"><Button variant="outline" onClick={() => setNovaNota(true)} disabled={!pedidoId}><Banknote className="mr-2 h-4 w-4" />Nota fiscal</Button><Button onClick={() => setNovaMedicao(true)} disabled={!pedidoId}><Plus className="mr-2 h-4 w-4" />Medição</Button></div>} /><PedidoSelect pedidos={pedidos} value={pedidoId} onChange={setPedidoId} />
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><MetricCard label="Valor aprovado" value={moneyBr(medido)} /><MetricCard label="Faturado" value={moneyBr(faturado)} /><MetricCard label="Recebido" value={moneyBr(recebido)} tone="success" /><MetricCard label="Vencido" value={moneyBr(vencido)} tone={vencido ? "danger" : "default"} /></div>
  <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Medições</CardTitle></CardHeader><CardContent className="space-y-2">{medicoes.length ? medicoes.map((m) => <div key={m.id} className="flex items-center justify-between border-b py-2"><div><div className="font-mono text-sm font-semibold">{m.numero}</div><div className="text-xs text-muted-foreground">{dateBr(m.periodo_inicio)} a {dateBr(m.periodo_fim)} · {moneyBr(m.valor_medido)}</div></div><div className="flex gap-2"><Badge variant="outline">{m.status}</Badge>{m.status === "rascunho" && <Button size="sm" variant="outline" onClick={() => medicaoStatus.mutate({ id: m.id, status: "enviada" })}>Enviar</Button>}{m.status === "enviada" && <Button size="sm" onClick={() => medicaoStatus.mutate({ id: m.id, status: "aprovada" })}>Aprovar</Button>}</div></div>) : <Empty text="Nenhuma medição registrada." />}</CardContent></Card>
  <Card><CardHeader><CardTitle className="text-base">Notas fiscais e pagamentos</CardTitle></CardHeader><CardContent className="space-y-2">{notas.length ? notas.map((n) => <div key={n.id} className="flex items-center justify-between border-b py-2"><div><div className="font-mono text-sm font-semibold">NF {n.numero}</div><div className="text-xs text-muted-foreground">Vence {dateBr(n.data_vencimento)} · {moneyBr(n.valor)}</div></div>{n.status === "paga" ? <Badge>Pago em {dateBr(n.data_pagamento)}</Badge> : <Button size="sm" onClick={() => pagar.mutate(n)}>Confirmar pagamento</Button>}</div>) : <Empty text="Nenhuma nota fiscal registrada." />}</CardContent></Card></div>
  {pedido && <Card><CardContent className="flex flex-wrap items-center justify-between gap-3 pt-6"><div><div className="text-sm font-semibold">Encerramento do {pedido.numero}</div><p className="text-xs text-muted-foreground">Exige todos os conjuntos expedidos e o valor integral recebido.</p></div><Button onClick={() => encerrar.mutate()} disabled={pedido.status === "concluido"}>{pedido.status === "concluido" ? "Pedido encerrado" : "Encerrar pedido"}</Button></CardContent></Card>}
  <Dialog open={novaMedicao} onOpenChange={setNovaMedicao}><DialogContent><DialogHeader><DialogTitle>Nova medição</DialogTitle></DialogHeader><Field label="Número"><Input value={mf.numero} onChange={(e) => setMf({ ...mf, numero: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Início do período"><Input type="date" value={mf.inicio} onChange={(e) => setMf({ ...mf, inicio: e.target.value })} /></Field><Field label="Fim do período"><Input type="date" value={mf.fim} onChange={(e) => setMf({ ...mf, fim: e.target.value })} /></Field></div><Field label="Valor medido"><Input type="number" step="0.01" value={mf.valor} onChange={(e) => setMf({ ...mf, valor: e.target.value })} /></Field><Field label="Observações"><Textarea value={mf.observacoes} onChange={(e) => setMf({ ...mf, observacoes: e.target.value })} /></Field><DialogFooter><Button variant="outline" onClick={() => setNovaMedicao(false)}>Cancelar</Button><Button onClick={() => criarMedicao.mutate()}>Criar</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={novaNota} onOpenChange={setNovaNota}><DialogContent><DialogHeader><DialogTitle>Registrar nota fiscal</DialogTitle></DialogHeader><Field label="Medição"><Select value={nf.medicao_id} onValueChange={(v) => setNf({ ...nf, medicao_id: v })}><SelectTrigger><SelectValue placeholder="Opcional" /></SelectTrigger><SelectContent>{medicoes.filter((m) => m.status === "aprovada").map((m) => <SelectItem key={m.id} value={m.id}>{m.numero} · {moneyBr(m.valor_medido)}</SelectItem>)}</SelectContent></Select></Field><Field label="Número da NF"><Input value={nf.numero} onChange={(e) => setNf({ ...nf, numero: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Emissão"><Input type="date" value={nf.emissao} onChange={(e) => setNf({ ...nf, emissao: e.target.value })} /></Field><Field label="Vencimento"><Input type="date" value={nf.vencimento} onChange={(e) => setNf({ ...nf, vencimento: e.target.value })} /></Field></div><Field label="Valor"><Input type="number" step="0.01" value={nf.valor} onChange={(e) => setNf({ ...nf, valor: e.target.value })} /></Field><DialogFooter><Button variant="outline" onClick={() => setNovaNota(false)}>Cancelar</Button><Button onClick={() => criarNota.mutate()} disabled={!nf.numero}>Registrar</Button></DialogFooter></DialogContent></Dialog></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function Empty({ text }: { text: string }) { return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>; }