import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Factory, Pause, Play, Plus, Square } from "lucide-react";
import { toast } from "sonner";
import { MetricCard, ModuleHeader, PedidoSelect, PROCESSOS, ProgressBar, hoursBetween, processoLabel, useConjuntos, usePedidos } from "@/components/operations";

export const Route = createFileRoute("/_authenticated/producao")({
  head: () => ({ meta: [{ title: "Produção | Omega Service ERP" }, { name: "description", content: "Apontamentos de produção e controle de paralisações por pedido." }, { property: "og:title", content: "Produção | Omega Service ERP" }, { property: "og:description", content: "Apontamentos de produção e controle de paralisações por pedido." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ProducaoPage,
});

type Apontamento = { id: string; conjunto_id: string; processo: string; inicio: string; fim: string | null; status: string; quantidade_executada: number; peso_executado_kg: number | null };
type Paralisacao = { id: string; conjunto_id: string | null; motivo: string; detalhe: string | null; inicio: string; fim: string | null; duracao_horas: number | null };

function ProducaoPage() {
  const qc = useQueryClient(); const { data: pedidos = [] } = usePedidos(); const [pedidoId, setPedidoId] = useState(""); const [novo, setNovo] = useState(false); const [parar, setParar] = useState(false);
  const [form, setForm] = useState({ conjunto_id: "", processo: "corte", quantidade: "", peso: "" }); const [stop, setStop] = useState({ conjunto_id: "", motivo: "falta_material", detalhe: "" });
  useEffect(() => { if (!pedidoId && pedidos[0]) setPedidoId(pedidos[0].id); }, [pedidoId, pedidos]); const { data: conjuntos = [] } = useConjuntos(pedidoId);
  const { data: apontamentos = [] } = useQuery({ queryKey: ["apontamentos", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("apontamentos_producao").select("*").eq("pedido_id", pedidoId).order("created_at", { ascending: false }); if (error) throw error; return data as Apontamento[]; } });
  const { data: paralisacoes = [] } = useQuery({ queryKey: ["paralisacoes", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("paralisacoes").select("*").eq("pedido_id", pedidoId).order("inicio", { ascending: false }); if (error) throw error; return data as Paralisacao[]; } });
  const produtivas = apontamentos.reduce((s, a) => s + hoursBetween(a.inicio, a.fim), 0); const paradas = paralisacoes.reduce((s, p) => s + Number(p.duracao_horas ?? hoursBetween(p.inicio, p.fim)), 0); const eficiencia = produtivas + paradas ? produtivas / (produtivas + paradas) * 100 : 0;
  const active = apontamentos.filter((a) => a.status !== "concluido");
  const porConjunto = useMemo(() => new Map(conjuntos.map((c) => [c.id, c])), [conjuntos]);
  const iniciar = useMutation({ mutationFn: async () => { if (!pedidoId || !form.conjunto_id) throw new Error("Selecione o conjunto"); const res = await supabase.from("apontamentos_producao").insert({ pedido_id: pedidoId, conjunto_id: form.conjunto_id, processo: form.processo, quantidade_executada: Number(form.quantidade || 0), peso_executado_kg: form.peso ? Number(form.peso) : null }); if (res.error) throw res.error; await supabase.from("pedido_conjuntos").update({ status: "em_producao" }).eq("id", form.conjunto_id); await supabase.from("pedidos").update({ status: "em_producao" }).eq("id", pedidoId); }, onSuccess: () => { toast.success("Processo iniciado"); setNovo(false); qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  const concluir = useMutation({ mutationFn: async (a: Apontamento) => { const res = await supabase.from("apontamentos_producao").update({ status: "concluido", fim: new Date().toISOString() }).eq("id", a.id); if (res.error) throw res.error; const feitos = new Set(apontamentos.filter((x) => x.conjunto_id === a.conjunto_id && (x.status === "concluido" || x.id === a.id)).map((x) => x.processo)); const progresso = Math.min(75, feitos.size / PROCESSOS.length * 75); await supabase.from("pedido_conjuntos").update({ progresso, status: progresso >= 75 ? "aguardando_qualidade" : "em_producao" }).eq("id", a.conjunto_id); }, onSuccess: () => { toast.success("Processo concluído"); qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  const registrarParada = useMutation({ mutationFn: async () => { if (!pedidoId) return; const res = await supabase.from("paralisacoes").insert({ pedido_id: pedidoId, conjunto_id: stop.conjunto_id || null, motivo: stop.motivo, detalhe: stop.detalhe || null }); if (res.error) throw res.error; }, onSuccess: () => { toast.success("Paralisação iniciada"); setParar(false); qc.invalidateQueries({ queryKey: ["paralisacoes", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  const encerrarParada = useMutation({ mutationFn: async (id: string) => { const res = await supabase.from("paralisacoes").update({ fim: new Date().toISOString() }).eq("id", id); if (res.error) throw res.error; }, onSuccess: () => qc.invalidateQueries({ queryKey: ["paralisacoes", pedidoId] }), onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-6"><ModuleHeader title="Produção" description="Execução dos processos e registro do tempo produtivo e de paralisação." icon={Factory} action={<div className="flex gap-2"><Button variant="outline" onClick={() => setParar(true)} disabled={!pedidoId}><Pause className="mr-2 h-4 w-4" />Paralisação</Button><Button onClick={() => setNovo(true)} disabled={!pedidoId || !conjuntos.length}><Play className="mr-2 h-4 w-4" />Iniciar processo</Button></div>} /><PedidoSelect pedidos={pedidos} value={pedidoId} onChange={setPedidoId} />
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><MetricCard label="Em andamento" value={active.length} /><MetricCard label="Horas produtivas" value={produtivas.toFixed(1)} tone="success" /><MetricCard label="Horas paradas" value={paradas.toFixed(1)} tone={paradas ? "warning" : "default"} /><MetricCard label="Eficiência" value={`${eficiencia.toFixed(0)}%`} /></div>
  <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Conjuntos e avanço</CardTitle></CardHeader><CardContent className="space-y-3">{conjuntos.length ? conjuntos.map((c) => <div key={c.id} className="space-y-2 border-b pb-3"><div className="flex justify-between gap-3"><div><span className="font-mono text-sm font-semibold">{c.tag}</span><p className="text-xs text-muted-foreground">{c.descricao}</p></div><Badge variant={c.status === "aguardando_qualidade" ? "default" : "outline"}>{c.status.replaceAll("_", " ")}</Badge></div><ProgressBar value={c.progresso} /></div>) : <Empty text="O PCP ainda não cadastrou conjuntos." />}</CardContent></Card>
  <Card><CardHeader><CardTitle className="text-base">Apontamentos recentes</CardTitle></CardHeader><CardContent className="space-y-2">{apontamentos.length ? apontamentos.slice(0, 10).map((a) => <div key={a.id} className="flex items-center justify-between border-b py-2"><div><div className="text-sm font-medium">{porConjunto.get(a.conjunto_id)?.tag ?? "TAG"} · {processoLabel(a.processo)}</div><div className="text-xs text-muted-foreground">{new Date(a.inicio).toLocaleString("pt-BR")} · {hoursBetween(a.inicio, a.fim).toFixed(1)}h</div></div>{a.status !== "concluido" ? <Button size="sm" variant="outline" onClick={() => concluir.mutate(a)}><Square className="mr-2 h-3 w-3" />Concluir</Button> : <Badge variant="outline">Concluído</Badge>}</div>) : <Empty text="Nenhum processo apontado." />}</CardContent></Card></div>
  <Card><CardHeader><CardTitle className="text-base">Paralisações</CardTitle></CardHeader><CardContent className="space-y-2">{paralisacoes.length ? paralisacoes.map((p) => <div key={p.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-2"><div><div className="text-sm font-medium">{p.motivo.replaceAll("_", " ")} · {p.conjunto_id ? porConjunto.get(p.conjunto_id)?.tag : "Pedido"}</div><div className="text-xs text-muted-foreground">{p.detalhe || "Sem detalhe"}</div></div>{p.fim ? <Badge variant="outline">{Number(p.duracao_horas).toFixed(1)}h</Badge> : <Button size="sm" variant="destructive" onClick={() => encerrarParada.mutate(p.id)}>Encerrar parada</Button>}</div>) : <Empty text="Nenhuma paralisação registrada." />}</CardContent></Card>
  <Dialog open={novo} onOpenChange={setNovo}><DialogContent><DialogHeader><DialogTitle>Iniciar processo</DialogTitle></DialogHeader><SelectField label="Conjunto" value={form.conjunto_id} onChange={(v) => setForm({ ...form, conjunto_id: v })} options={conjuntos.map((c) => ({ value: c.id, label: `${c.tag} · ${c.descricao}` }))} /><SelectField label="Processo" value={form.processo} onChange={(v) => setForm({ ...form, processo: v })} options={PROCESSOS.map((p) => ({ value: p, label: processoLabel(p) }))} /><div className="grid grid-cols-2 gap-3"><Field label="Quantidade"><Input type="number" value={form.quantidade} onChange={(e) => setForm({ ...form, quantidade: e.target.value })} /></Field><Field label="Peso executado (kg)"><Input type="number" value={form.peso} onChange={(e) => setForm({ ...form, peso: e.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setNovo(false)}>Cancelar</Button><Button onClick={() => iniciar.mutate()} disabled={!form.conjunto_id}>Iniciar</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={parar} onOpenChange={setParar}><DialogContent><DialogHeader><DialogTitle>Registrar paralisação</DialogTitle></DialogHeader><SelectField label="Conjunto" value={stop.conjunto_id} onChange={(v) => setStop({ ...stop, conjunto_id: v })} options={[{ value: "pedido", label: "Pedido inteiro" }, ...conjuntos.map((c) => ({ value: c.id, label: c.tag }))]} /><SelectField label="Motivo" value={stop.motivo} onChange={(v) => setStop({ ...stop, motivo: v })} options={["falta_material","manutencao","absenteismo","projeto","qualidade","energia","outros"].map((v) => ({ value: v, label: v.replaceAll("_", " ") }))} /><Field label="Detalhes"><Textarea value={stop.detalhe} onChange={(e) => setStop({ ...stop, detalhe: e.target.value })} /></Field><DialogFooter><Button variant="outline" onClick={() => setParar(false)}>Cancelar</Button><Button onClick={() => { if (stop.conjunto_id === "pedido") setStop({ ...stop, conjunto_id: "" }); registrarParada.mutate(); }}>Iniciar paralisação</Button></DialogFooter></DialogContent></Dialog></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: { value: string; label: string }[] }) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{options.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></Field>; }
function Empty({ text }: { text: string }) { return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>; }