import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ShieldCheck, Plus, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { MetricCard, ModuleHeader, PedidoSelect, dateBr, useConjuntos, usePedidos } from "@/components/operations";

export const Route = createFileRoute("/_authenticated/qualidade")({
  head: () => ({ meta: [{ title: "Qualidade | Omega Service ERP" }, { name: "description", content: "Inspeções, não conformidades e liberação de conjuntos." }, { property: "og:title", content: "Qualidade | Omega Service ERP" }, { property: "og:description", content: "Inspeções, não conformidades e liberação de conjuntos." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: QualidadePage,
});

type Inspecao = { id: string; conjunto_id: string; tipo: string; resultado: string; data_inspecao: string; observacoes: string | null; reinspecao_de: string | null };
type Nc = { id: string; inspecao_id: string; conjunto_id: string; descricao: string; acao_corretiva: string | null; exige_retrabalho: boolean; status: string };

function QualidadePage() {
  const qc = useQueryClient(); const { data: pedidos = [] } = usePedidos(); const [pedidoId, setPedidoId] = useState(""); const [open, setOpen] = useState(false); const [ncInspecao, setNcInspecao] = useState<Inspecao | null>(null);
  const [form, setForm] = useState({ conjunto_id: "", tipo: "dimensional", resultado: "aprovado", observacoes: "", reinspecao_de: "" }); const [ncForm, setNcForm] = useState({ descricao: "", acao_corretiva: "", exige_retrabalho: true });
  useEffect(() => { if (!pedidoId && pedidos[0]) setPedidoId(pedidos[0].id); }, [pedidoId, pedidos]); const { data: conjuntos = [] } = useConjuntos(pedidoId);
  const { data: inspecoes = [] } = useQuery({ queryKey: ["inspecoes", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("inspecoes_qualidade").select("*").eq("pedido_id", pedidoId).order("created_at", { ascending: false }); if (error) throw error; return data as Inspecao[]; } });
  const { data: ncs = [] } = useQuery({ queryKey: ["ncs", pedidoId], enabled: Boolean(pedidoId), queryFn: async () => { const { data, error } = await supabase.from("nao_conformidades").select("*").eq("pedido_id", pedidoId).order("created_at", { ascending: false }); if (error) throw error; return data as Nc[]; } });
  const cmap = useMemo(() => new Map(conjuntos.map((c) => [c.id, c])), [conjuntos]); const fila = conjuntos.filter((c) => c.status === "aguardando_qualidade" || !c.liberado_qualidade); const aprovadas = inspecoes.filter((i) => i.resultado === "aprovado").length; const reprovadas = inspecoes.filter((i) => i.resultado === "reprovado").length;
  const salvar = useMutation({ mutationFn: async () => { if (!pedidoId || !form.conjunto_id) throw new Error("Selecione o conjunto"); const { error } = await supabase.from("inspecoes_qualidade").insert({ pedido_id: pedidoId, conjunto_id: form.conjunto_id, tipo: form.tipo, resultado: form.resultado, observacoes: form.observacoes || null, reinspecao_de: form.reinspecao_de || null }); if (error) throw error; }, onSuccess: () => { toast.success(form.resultado === "aprovado" && form.tipo === "final" ? "Conjunto liberado" : "Inspeção registrada"); setOpen(false); setForm({ conjunto_id: "", tipo: "dimensional", resultado: "aprovado", observacoes: "", reinspecao_de: "" }); qc.invalidateQueries(); }, onError: (e: Error) => toast.error(e.message) });
  const criarNc = useMutation({ mutationFn: async () => { if (!pedidoId || !ncInspecao) return; const { error } = await supabase.from("nao_conformidades").insert({ inspecao_id: ncInspecao.id, pedido_id: pedidoId, conjunto_id: ncInspecao.conjunto_id, descricao: ncForm.descricao, acao_corretiva: ncForm.acao_corretiva || null, exige_retrabalho: ncForm.exige_retrabalho }); if (error) throw error; }, onSuccess: () => { toast.success("Não conformidade aberta"); setNcInspecao(null); setNcForm({ descricao: "", acao_corretiva: "", exige_retrabalho: true }); qc.invalidateQueries({ queryKey: ["ncs", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  const encerrarNc = useMutation({ mutationFn: async (id: string) => { const { error } = await supabase.from("nao_conformidades").update({ status: "encerrada" }).eq("id", id); if (error) throw error; }, onSuccess: () => { toast.success("Não conformidade encerrada"); qc.invalidateQueries({ queryKey: ["ncs", pedidoId] }); }, onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-6"><ModuleHeader title="Qualidade" description="Inspeções, retrabalhos, não conformidades e liberação final." icon={ShieldCheck} action={<Button onClick={() => setOpen(true)} disabled={!pedidoId || !conjuntos.length}><Plus className="mr-2 h-4 w-4" />Nova inspeção</Button>} /><PedidoSelect pedidos={pedidos} value={pedidoId} onChange={setPedidoId} />
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><MetricCard label="Fila de inspeção" value={fila.length} /><MetricCard label="Aprovadas" value={aprovadas} tone="success" /><MetricCard label="Reprovadas" value={reprovadas} tone={reprovadas ? "danger" : "default"} /><MetricCard label="NCs abertas" value={ncs.filter((n) => n.status !== "encerrada").length} tone="warning" /></div>
  <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Fila por conjunto</CardTitle></CardHeader><CardContent className="space-y-2">{conjuntos.length ? conjuntos.map((c) => <div key={c.id} className="flex items-center justify-between border-b py-2"><div><div className="font-mono text-sm font-semibold">{c.tag}</div><div className="text-xs text-muted-foreground">{c.descricao}</div></div><Badge variant={c.liberado_qualidade ? "default" : "outline"}>{c.liberado_qualidade ? "Liberado" : "Aguardando"}</Badge></div>) : <Empty text="Nenhum conjunto cadastrado." />}</CardContent></Card>
  <Card><CardHeader><CardTitle className="text-base">Inspeções realizadas</CardTitle></CardHeader><CardContent className="space-y-2">{inspecoes.length ? inspecoes.map((i) => <div key={i.id} className="flex items-center justify-between gap-2 border-b py-2"><div><div className="text-sm font-medium">{cmap.get(i.conjunto_id)?.tag} · {i.tipo}</div><div className="text-xs text-muted-foreground">{dateBr(i.data_inspecao)}{i.reinspecao_de ? " · reinspeção" : ""}</div></div><div className="flex items-center gap-2"><Badge variant={i.resultado === "reprovado" ? "destructive" : i.resultado === "aprovado" ? "default" : "outline"}>{i.resultado}</Badge>{i.resultado === "reprovado" && !ncs.some((n) => n.inspecao_id === i.id) && <Button size="sm" variant="outline" onClick={() => setNcInspecao(i)}>Abrir NC</Button>}<Button size="icon" variant="ghost" title="Reinspecionar" onClick={() => { setForm({ conjunto_id: i.conjunto_id, tipo: i.tipo, resultado: "aprovado", observacoes: "", reinspecao_de: i.id }); setOpen(true); }}><RotateCcw className="h-4 w-4" /></Button></div></div>) : <Empty text="Nenhuma inspeção registrada." />}</CardContent></Card></div>
  <Card><CardHeader><CardTitle className="text-base">Não conformidades</CardTitle></CardHeader><CardContent className="space-y-2">{ncs.length ? ncs.map((n) => <div key={n.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-2"><div><div className="text-sm font-medium">{cmap.get(n.conjunto_id)?.tag} · {n.descricao}</div><div className="text-xs text-muted-foreground">{n.acao_corretiva || "Ação corretiva pendente"}{n.exige_retrabalho ? " · requer retrabalho" : ""}</div></div>{n.status === "encerrada" ? <Badge variant="outline">Encerrada</Badge> : <Button size="sm" onClick={() => encerrarNc.mutate(n.id)}>Encerrar NC</Button>}</div>) : <Empty text="Nenhuma não conformidade." />}</CardContent></Card>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{form.reinspecao_de ? "Reinspeção" : "Nova inspeção"}</DialogTitle></DialogHeader><SelectField label="Conjunto" value={form.conjunto_id} onChange={(v) => setForm({ ...form, conjunto_id: v })} options={conjuntos.map((c) => ({ value: c.id, label: `${c.tag} · ${c.descricao}` }))} /><SelectField label="Tipo" value={form.tipo} onChange={(v) => setForm({ ...form, tipo: v })} options={["dimensional","soldagem","pintura","final"].map((v) => ({ value: v, label: v }))} /><SelectField label="Resultado" value={form.resultado} onChange={(v) => setForm({ ...form, resultado: v })} options={["pendente","aprovado","reprovado"].map((v) => ({ value: v, label: v }))} /><Field label="Observações"><Textarea value={form.observacoes} onChange={(e) => setForm({ ...form, observacoes: e.target.value })} /></Field><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => salvar.mutate()} disabled={!form.conjunto_id}>Registrar</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(ncInspecao)} onOpenChange={(o) => !o && setNcInspecao(null)}><DialogContent><DialogHeader><DialogTitle>Abrir não conformidade</DialogTitle></DialogHeader><Field label="Descrição"><Textarea value={ncForm.descricao} onChange={(e) => setNcForm({ ...ncForm, descricao: e.target.value })} /></Field><Field label="Ação corretiva"><Textarea value={ncForm.acao_corretiva} onChange={(e) => setNcForm({ ...ncForm, acao_corretiva: e.target.value })} /></Field><DialogFooter><Button variant="outline" onClick={() => setNcInspecao(null)}>Cancelar</Button><Button variant="destructive" onClick={() => criarNc.mutate()} disabled={!ncForm.descricao}>Abrir NC</Button></DialogFooter></DialogContent></Dialog></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: { value: string; label: string }[] }) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{options.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></Field>; }
function Empty({ text }: { text: string }) { return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>; }