/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQualidadeRouteImport } from './routes/_authenticated/qualidade'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedPcpRouteImport } from './routes/_authenticated/pcp'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedMedicaoRouteImport } from './routes/_authenticated/medicao'
import { Route as AuthenticatedExpedicaoRouteImport } from './routes/_authenticated/expedicao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCadastrosFuncionariosRouteImport } from './routes/_authenticated/cadastros/funcionarios'
import { Route as AuthenticatedCadastrosEquipamentosRouteImport } from './routes/_authenticated/cadastros/equipamentos'
import { Route as AuthenticatedCadastrosContratosRouteImport } from './routes/_authenticated/cadastros/contratos'
import { Route as AuthenticatedCadastrosClientesRouteImport } from './routes/_authenticated/cadastros/clientes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQualidadeRoute = AuthenticatedQualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPcpRoute = AuthenticatedPcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicaoRoute = AuthenticatedMedicaoRouteImport.update({
  id: '/medicao',
  path: '/medicao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpedicaoRoute = AuthenticatedExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosFuncionariosRoute =
  AuthenticatedCadastrosFuncionariosRouteImport.update({
    id: '/cadastros/funcionarios',
    path: '/cadastros/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosEquipamentosRoute =
  AuthenticatedCadastrosEquipamentosRouteImport.update({
    id: '/cadastros/equipamentos',
    path: '/cadastros/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosContratosRoute =
  AuthenticatedCadastrosContratosRouteImport.update({
    id: '/cadastros/contratos',
    path: '/cadastros/contratos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosClientesRoute =
  AuthenticatedCadastrosClientesRouteImport.update({
    id: '/cadastros/clientes',
    path: '/cadastros/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expedicao': typeof AuthenticatedExpedicaoRoute
  '/medicao': typeof AuthenticatedMedicaoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pcp': typeof AuthenticatedPcpRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/qualidade': typeof AuthenticatedQualidadeRoute
  '/cadastros/clientes': typeof AuthenticatedCadastrosClientesRoute
  '/cadastros/contratos': typeof AuthenticatedCadastrosContratosRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/funcionarios': typeof AuthenticatedCadastrosFuncionariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expedicao': typeof AuthenticatedExpedicaoRoute
  '/medicao': typeof AuthenticatedMedicaoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pcp': typeof AuthenticatedPcpRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/qualidade': typeof AuthenticatedQualidadeRoute
  '/cadastros/clientes': typeof AuthenticatedCadastrosClientesRoute
  '/cadastros/contratos': typeof AuthenticatedCadastrosContratosRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/funcionarios': typeof AuthenticatedCadastrosFuncionariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expedicao': typeof AuthenticatedExpedicaoRoute
  '/_authenticated/medicao': typeof AuthenticatedMedicaoRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pcp': typeof AuthenticatedPcpRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/qualidade': typeof AuthenticatedQualidadeRoute
  '/_authenticated/cadastros/clientes': typeof AuthenticatedCadastrosClientesRoute
  '/_authenticated/cadastros/contratos': typeof AuthenticatedCadastrosContratosRoute
  '/_authenticated/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/_authenticated/cadastros/funcionarios': typeof AuthenticatedCadastrosFuncionariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/expedicao'
    | '/medicao'
    | '/orcamentos'
    | '/pcp'
    | '/producao'
    | '/qualidade'
    | '/cadastros/clientes'
    | '/cadastros/contratos'
    | '/cadastros/equipamentos'
    | '/cadastros/funcionarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/expedicao'
    | '/medicao'
    | '/orcamentos'
    | '/pcp'
    | '/producao'
    | '/qualidade'
    | '/cadastros/clientes'
    | '/cadastros/contratos'
    | '/cadastros/equipamentos'
    | '/cadastros/funcionarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/expedicao'
    | '/_authenticated/medicao'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pcp'
    | '/_authenticated/producao'
    | '/_authenticated/qualidade'
    | '/_authenticated/cadastros/clientes'
    | '/_authenticated/cadastros/contratos'
    | '/_authenticated/cadastros/equipamentos'
    | '/_authenticated/cadastros/funcionarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/qualidade': {
      id: '/_authenticated/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof AuthenticatedQualidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pcp': {
      id: '/_authenticated/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof AuthenticatedPcpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicao': {
      id: '/_authenticated/medicao'
      path: '/medicao'
      fullPath: '/medicao'
      preLoaderRoute: typeof AuthenticatedMedicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedicao': {
      id: '/_authenticated/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof AuthenticatedExpedicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/funcionarios': {
      id: '/_authenticated/cadastros/funcionarios'
      path: '/cadastros/funcionarios'
      fullPath: '/cadastros/funcionarios'
      preLoaderRoute: typeof AuthenticatedCadastrosFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/equipamentos': {
      id: '/_authenticated/cadastros/equipamentos'
      path: '/cadastros/equipamentos'
      fullPath: '/cadastros/equipamentos'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/contratos': {
      id: '/_authenticated/cadastros/contratos'
      path: '/cadastros/contratos'
      fullPath: '/cadastros/contratos'
      preLoaderRoute: typeof AuthenticatedCadastrosContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/clientes': {
      id: '/_authenticated/cadastros/clientes'
      path: '/cadastros/clientes'
      fullPath: '/cadastros/clientes'
      preLoaderRoute: typeof AuthenticatedCadastrosClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpedicaoRoute: typeof AuthenticatedExpedicaoRoute
  AuthenticatedMedicaoRoute: typeof AuthenticatedMedicaoRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPcpRoute: typeof AuthenticatedPcpRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedQualidadeRoute: typeof AuthenticatedQualidadeRoute
  AuthenticatedCadastrosClientesRoute: typeof AuthenticatedCadastrosClientesRoute
  AuthenticatedCadastrosContratosRoute: typeof AuthenticatedCadastrosContratosRoute
  AuthenticatedCadastrosEquipamentosRoute: typeof AuthenticatedCadastrosEquipamentosRoute
  AuthenticatedCadastrosFuncionariosRoute: typeof AuthenticatedCadastrosFuncionariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpedicaoRoute: AuthenticatedExpedicaoRoute,
  AuthenticatedMedicaoRoute: AuthenticatedMedicaoRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPcpRoute: AuthenticatedPcpRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedQualidadeRoute: AuthenticatedQualidadeRoute,
  AuthenticatedCadastrosClientesRoute: AuthenticatedCadastrosClientesRoute,
  AuthenticatedCadastrosContratosRoute: AuthenticatedCadastrosContratosRoute,
  AuthenticatedCadastrosEquipamentosRoute:
    AuthenticatedCadastrosEquipamentosRoute,
  AuthenticatedCadastrosFuncionariosRoute:
    AuthenticatedCadastrosFuncionariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
